@startuml
left to right direction
actor UsuárioVisitante as uv
actor Sistema as sys
package UsuárioLogado as ul{
  actor Professor as p
  actor Administrador as adm
  actor Aluno as al
}
package AppDivisãoDeEstágio {
  usecase "Ver Perfil" as UC1

  usecase "Ver Modelo de Relatório" as UC3
  usecase "Iniciar cadastro de estágio" as UC4
  usecase "Casdrastrar empresa" as UC5
  usecase "Ver Perfil de Professor" as UC6
  usecase "Acompanhar entrega de relatório" as UC7
  usecase "Assinar relatório" as UC8
  usecase "Aprovar castrastro de empresa" as UC9

  usecase "Registrar duvida" as UC11
  usecase "Responder dúvida" as UC12
  usecase "Assinar aprovação de relatório" as UC13
  usecase "Cadastrar Professor" as UC14
  usecase "Editar Perfil" as UC15
  usecase "Coletar Assinatura" as UC16
  usecase "Fazer Login" as UC17
  usecase "Cadastrar Aluno" as UC18
  usecase "Ver Solicitações de Empresas" as UC19
  usecase "Ver Solicitações de Alunos" as UC20
  usecase "Ver Lista de Professores" as UC21
  usecase "Ver Lista de Alunos" as UC22
  usecase "Ver Solicitações de Alunos" as UC23
  usecase "Fazer Logout" as UC24
  usecase "Ver Notas" as UC25
}

UC16 <-- sys


adm --> UC6
adm --> UC9

adm --> UC12
adm --> UC13
adm --> UC14
adm --> UC15
adm --> UC15
adm --> UC19
adm --> UC21
adm --> UC22


p --> UC7
p --> UC8
p --> UC13
p --> UC20
p --> UC23

al --> UC3
al --> UC4
al --> UC5
al --> UC6
al --> UC7

al --> UC11
al --> UC25

uv --> UC17
uv --> UC18

ul --> UC1
ul --> UC15
ul --> UC24
@enduml
