@startuml
left to right direction
actor UsuárioVisitante as uv
actor Sistema as sys
package UsuárioLogado as ul{
  actor Professor as p
  actor Administrador as adm
  actor Aluno as al
}
package AppDivisãoDeEstágio {
  usecase "Ver Perfil" as UC1
  usecase "Ver Modelo de Relatório" as UC2
  usecase "Iniciar cadastro de estágio" as UC3
  usecase "Casdrastrar empresa" as UC4
  usecase "Ver Perfil de Professor" as UC5
  usecase "Acompanhar entrega de relatório" as UC6
  usecase "Assinar relatório" as UC7
  usecase "Aprovar castrastro de empresa" as UC8
  usecase "Assinar aprovação de relatório" as UC9
  usecase "Cadastrar Professor" as UC10
  usecase "Editar Perfil" as UC11
  usecase "Coletar Assinatura" as UC12
  usecase "Fazer Login" as UC13
  usecase "Cadastrar Aluno" as UC14
  usecase "Ver Solicitações de Empresas" as UC15
  usecase "Ver Solicitações de Alunos" as UC16
  usecase "Ver Professores" as UC17
  usecase "Ver Alunos" as UC18
  usecase "Ver Solicitações de Alunos" as UC19
  usecase "Fazer Logout" as UC20
  usecase "Ver Notas" as UC21
  usecase "Ver Perfil do Aluno" as UC22
  usecase "Ver Perfil do Professor" as UC23
}

UC12 <-- sys


adm --> UC5
adm --> UC8
adm --> UC9
adm --> UC10
adm --> UC15
adm --> UC17
adm --> UC18
adm --> UC22
adm --> UC23


p --> UC6
p --> UC7
p --> UC13
p --> UC16
p --> UC18
p --> UC19
p --> UC22

al --> UC2
al --> UC3
al --> UC4
al --> UC5
al --> UC6
al --> UC21
al --> UC23

uv --> UC13
uv --> UC14

ul --> UC1
ul --> UC11
ul --> UC20
@enduml
